In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("raw_data.csv")

###### df

In [7]:
df2=df.copy()

df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 50000 else "10%")

gender_map ={"Male" : "M" ,"Female" : "F", "Unknown" : "U"}


df2["gender"] =df2["gender"].map(gender_map)

df2 =df2.assign(new_income = df2["income"] * 1.1)

#we can replace our existing value
df2["country"] = df2["country"].replace("USA", "United States")

In [9]:
df2

    id          name   age        country gender   income  tax  new_income
0    1      John Doe  29.0  United States      M  55000.0  20%     60500.0
1    1      John Doe  29.0  United States      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN         Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0          China      M  51000.0  20%     56100.0
6    6           NaN  45.0          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States    NaN  58000.0  20%     63800.0

In [11]:
df2.columns = ["Id","Name","Age","Country","Gender","Income","Tax","New_Income"]
#it is use to chane the name of column

In [13]:
df2

    Id          Name   Age        Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0  United States      M  55000.0  20%     60500.0
1    1      John Doe  29.0  United States      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN         Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0          China      M  51000.0  20%     56100.0
6    6           NaN  45.0          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States    NaN  58000.0  20%     63800.0

In [15]:
#sorting
df2["Income"].sort_values()

9     45000.0
3     47000.0
5     51000.0
1     55000.0
0     55000.0
10    58000.0
2     62000.0
8     62000.0
7     68000.0
6     73000.0
4         NaN
Name: Income, dtype: float64

In [17]:
df2.sort_values(by=["Income", "Age"], ascending=False)
#sort index value
sorted_df = df2.sort_values(by=["Income", "Age"], ascending=False)
sorted_df.reset_index()

,index,Id,Name,Age,Country,Gender,Income,Tax,New_Income
0,6,6,NaN,45.0,India,F,73000.0,20%,80300.0
1,7,7,Ahmed Khan,38.0,NaN,M,68000.0,20%,74800.0
2,8,8,Rachel Lee,29.0,United States,F,62000.0,20%,68200.0
3,2,2,Jane Smith,NaN,Canada,F,62000.0,20%,68200.0
4,10,10,Emily Davis,31.0,United States,NaN,58000.0,20%,63800.0
5,0,1,John Doe,29.0,United States,M,55000.0,20%,60500.0
6,1,1,John Doe,29.0,United States,M,55000.0,20%,60500.0
7,5,5,Li Wei,27.0,China,M,51000.0,20%,56100.0
8,3,3,Alex,NaN,United States,U,47000.0,10%,51700.0
9,9,9,Carlos Ruiz,NaN,Mexico,M,45000.0,10%,49500.0
10,4,4,Maria Garcia,34.0,Spain,F,NaN,10%,NaN