In [71]:
#shift id column at the end

In [43]:
import pandas as pd

In [45]:
df = pd.read_csv("raw_data.csv")

In [47]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [53]:
df2=df.copy()
new_col = [col for col in df2.columns if col != "id"] + ["id"]
df2[new_col]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [55]:
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [22]:
#writing data to csv and json

In [78]:
#1st clean the data [remove the duplicates]
df2 = df.copy()

df2 = df2.drop_duplicates()
df2 = df2.fillna(0)

In [80]:
df2 = df2.sort_values("income")
df2 = df2.reset_index(drop = True)

In [82]:
df2.to_csv("sorted_data.csv")

In [84]:
df2

   id          name   age country   gender   income
0   4  Maria Garcia  34.0   Spain   Female      0.0
1   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2   3          Alex   0.0     USA  Unknown  47000.0
3   5        Li Wei  27.0   China     Male  51000.0
4   1      John Doe  29.0     USA     Male  55000.0
5  10   Emily Davis  31.0     USA        0  58000.0
6   2    Jane Smith   0.0  Canada   Female  62000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   7    Ahmed Khan  38.0       0     Male  68000.0
9   6             0  45.0   India   Female  73000.0

In [87]:
## Grouping & Aggregation of Data
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [91]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

#this all is used to help apply in the specific column
df.groupby("gender")["income"].mean()
df.groupby("gender")["income"].max()

gender
Female     73000.0
Male       68000.0
Unknown    47000.0
Name: income, dtype: float64

In [93]:
# to apply in all the column we use agg()
df.groupby("country")["income"].agg(["mean", "min" , "max"])

            mean      min      max
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  47000.0  62000.0

In [95]:
df.groupby("country")["income"].agg(avg_salary="mean", min_salary ="min", max_salary ="max")

         avg_salary  min_salary  max_salary
country
Canada      62000.0     62000.0     62000.0
China       51000.0     51000.0     51000.0
India       73000.0     73000.0     73000.0
Mexico      45000.0     45000.0     45000.0
Spain           NaN         NaN         NaN
USA         55400.0     47000.0     62000.0

In [101]:
#we can use different aggregate function in column
df.groupby("country").agg({
    "income" : "mean",
    "age" : "mean"
})
df.groupby("country").agg({
    "income" : "max",
    "age" : "mean"
})

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      62000.0  29.5