In [11]:
import requests

URL ="https://www.scrapethissite.com/pages/simple/"
res = requests.get(URL)

In [12]:
if res.status_code == 200:
    print(res.headers)
    
with open("scraped_data/data1.html", "w", encoding="utf-8") as f:
    f.write(res.text)

{'Date': 'Fri, 27 Feb 2026 10:54:26 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=PdqYR5IlaYJ7KY6TgWW4fetSbyIIVT2ulq8ZswClRfI%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1772189666"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=PdqYR5IlaYJ7KY6TgWW4fetSbyIIVT2ulq8ZswClRfI%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1772189666"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'br', 'CF-RAY': '9d4724e4dae3c1c8-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

In [17]:
pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------- ----------- 2.9/4.0 MB 32.2 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 8.9 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 9.2 MB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
from bs4 import BeautifulSoup
with open("Scraped_data/data1.html", "r") as f:
    html_content = f.read()

soup = BeautifulSoup(html_content, "lxml")

In [8]:
all_h3 = soup. find_all("h3")

for h3 in all_h3:
    name = h3.get_text(strip=True)
    print(h3.find_parent("div") ["class"])
    #print(h3.find_next("div").select("span.country-population")[0].get_text(strip=True))

['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']
['col-md-4', 'country']

In [10]:
#stores population

In [16]:
all_h3 = soup.find_all("h3")

all_countries =[]

for h3 in all_h3:
    name = h3.get_text(strip=True)
    # print(h3.find_parent("div") ["class"])
    population = h3. find_next("div").select("span.country-population") [0].get_text(strip=True)
    print(h3. find_next("div").select_one("span.country-population").get_text(strip=True) )

    all_countries.append([name, population])

84000
4975593
29121286
86754
13254
2986952
2968000
13068161
0
41343201
57881
8205000
21515754
71566
26711
8303512
4590000
285653
156118464
10403000
16241811
7148785
738004
9863117
9056010
8450
65365
395027
9947418
18012
201103330
301790
699847
0
2029307
9685000
314522
33679000
628
70916439
4844927
3039126
7581000
21058798
21388
16746491
19294149
1330044000
47790000
4516220
11423000
508659
141766
1500
1102677
10476000
81802257
740528
5484000
72813
9823821
34586184
14790608
1291170
80471869
273008
5792984
46505963
88013491
5244000
875983
2638
107708
48228
64768389
1545255
62348447
107818
4630000
195506
65228
24339838
27884
56375
1593256
10324025
443000
1014999
11000000
30
13550440
159358
1565126
748486
6898686
0
7989415
4491000
9648924
9982000
242968342
4622917
7353985
75049
1173108018
4000
29671605
76923300
308910
60340328
90812
2847232
6407085
127288000
40046566
5776500
14453680
92533
773407
51134
22912177
48422644
2789132
44270
15340000
6368162
4125247
160922
35000
21513990
3685076
1919552
2944459
497538
2217969
6461454
31627428
32965
4324000
666730
35925
21281844
65859
2062294
13796354
53414374
3086918
449198
53883
432900
3205060
9341
403000
1294104
395650
15447500
112468855
28274729
22061451
2128471
216494
15878271
1828
154000000
5995928
16645000
5009150
28951852
10065
2166
4252277
2967717
3410676
29907003
270485
6064515
99900177
184404791
38500000
7012
46
3916632
3800000
10676000
19907
6375830
840926
776948
21959278
7344847
140702000
11055976
25731776
559198
88340
35000000
9828655
4701069
7460
2007000
2550
5455000
5245695
31477
12323252
10112453
492829
8260490
175808
6052064
37429
22198110
1354051
20556
10543464
140
6587239
67089500
7487489
1466
1154625
4940916
10589025
122580
77804122
1228691
10472
22894384
41892895
45415596
33398682
0
310232863
3477000
27865738
921
104217
27223228
21730
108708
89571130
221552
16025
192001
1800000
23495361
159042
49000000
13460305
11651858

In [18]:
all_countries

[['Andorra', '84000'],
 ['United Arab Emirates', '4975593'],
 ['Afghanistan', '29121286'],
 ['Antigua and Barbuda', '86754'],
 ['Anguilla', '13254'],
 ['Albania', '2986952'],
 ['Armenia', '2968000'],
 ['Angola', '13068161'],
 ['Antarctica', '0'],
 ['Argentina', '41343201'],
 ['American Samoa', '57881'],
 ['Austria', '8205000'],
 ['Australia', '21515754'],
 ['Aruba', '71566'],
 ['Ã…land', '26711'],
 ['Azerbaijan', '8303512'],
 ['Bosnia and Herzegovina', '4590000'],
 ['Barbados', '285653'],
 ['Bangladesh', '156118464'],
 ['Belgium', '10403000'],
 ['Burkina Faso', '16241811'],
 ['Bulgaria', '7148785'],
 ['Bahrain', '738004'],
 ['Burundi', '9863117'],
 ['Benin', '9056010'],
 ['Saint BarthÃ©lemy', '8450'],
 ['Bermuda', '65365'],
 ['Brunei', '395027'],
 ['Bolivia', '9947418'],
 ['Bonaire', '18012'],
 ['Brazil', '201103330'],
 ['Bahamas', '301790'],
 ['Bhutan', '699847'],
 ['Bouvet Island', '0'],
 ['Botswana', '2029307'],
 ['Belarus', '9685000'],
 ['Belize', '314522'],
 ['Canada', '33679000'],
 ['Cocos [Keeling] Islands', '628'],
 ['Democratic Republic of the Congo', '70916439'],
 ['Central African Republic', '4844927'],
 ['Republic of the Congo', '3039126'],
 ['Switzerland', '7581000'],
 ['Ivory Coast', '21058798'],
 ['Cook Islands', '21388'],
 ['Chile', '16746491'],
 ['Cameroon', '19294149'],
 ['China', '1330044000'],
 ['Colombia', '47790000'],
 ['Costa Rica', '4516220'],
 ['Cuba', '11423000'],
 ['Cape Verde', '508659'],
 ['Curacao', '141766'],
 ['Christmas Island', '1500'],
 ['Cyprus', '1102677'],
 ['Czech Republic', '10476000'],
 ['Germany', '81802257'],
 ['Djibouti', '740528'],
 ['Denmark', '5484000'],
 ['Dominica', '72813'],
 ['Dominican Republic', '9823821'],
 ['Algeria', '34586184'],
 ['Ecuador', '14790608'],
 ['Estonia', '1291170'],
 ['Egypt', '80471869'],
 ['Western Sahara', '273008'],
 ['Eritrea', '5792984'],
 ['Spain', '46505963'],
 ['Ethiopia', '88013491'],
 ['Finland', '5244000'],
 ['Fiji', '875983'],
 ['Falkland Islands', '2638'],
 ['Micronesia', '107708'],
 ['Faroe Islands', '48228'],
 ['France', '64768389'],
 ['Gabon', '1545255'],
 ['United Kingdom', '62348447'],
 ['Grenada', '107818'],
 ['Georgia', '4630000'],
 ['French Guiana', '195506'],
 ['Guernsey', '65228'],
 ['Ghana', '24339838'],
 ['Gibraltar', '27884'],
 ['Greenland', '56375'],
 ['Gambia', '1593256'],
 ['Guinea', '10324025'],
 ['Guadeloupe', '443000'],
 ['Equatorial Guinea', '1014999'],
 ['Greece', '11000000'],
 ['South Georgia and the South Sandwich Islands', '30'],
 ['Guatemala', '13550440'],
 ['Guam', '159358'],
 ['Guinea-Bissau', '1565126'],
 ['Guyana', '748486'],
 ['Hong Kong', '6898686'],
 ['Heard Island and McDonald Islands', '0'],
 ['Honduras', '7989415'],
 ['Croatia', '4491000'],
 ['Haiti', '9648924'],
 ['Hungary', '9982000'],
 ['Indonesia', '242968342'],
 ['Ireland', '4622917'],
 ['Israel', '7353985'],
 ['Isle of Man', '75049'],
 ['India', '1173108018'],
 ['British Indian Ocean Territory', '4000'],
 ['Iraq', '29671605'],
 ['Iran', '76923300'],
 ['Iceland', '308910'],
 ['Italy', '60340328'],
 ['Jersey', '90812'],
 ['Jamaica', '2847232'],
 ['Jordan', '6407085'],
 ['Japan', '127288000'],
 ['Kenya', '40046566'],
 ['Kyrgyzstan', '5776500'],
 ['Cambodia', '14453680'],
 ['Kiribati', '92533'],
 ['Comoros', '773407'],
 ['Saint Kitts and Nevis', '51134'],
 ['North Korea', '22912177'],
 ['South Korea', '48422644'],
 ['Kuwait', '2789132'],
 ['Cayman Islands', '44270'],
 ['Kazakhstan', '15340000'],
 ['Laos', '6368162'],
 ['Lebanon', '4125247'],
 ['Saint Lucia', '160922'],
 ['Liechtenstein', '35000'],
 ['Sri Lanka', '21513990'],
 ['Liberia', '3685076'],
 ['Lesotho', '1919552'],
 ['Lithuania', '2944459'],
 ['Luxembourg', '497538'],
 ['Latvia', '2217969'],
 ['Libya', '6461454'],
 ['Morocco', '31627428'],
 ['Monaco', '32965'],
 ['Moldova', '4324000'],
 ['Montenegro', '666730'],
 ['Saint Martin', '35925'],
 ['Madagascar', '21281844'],
 ['Marshall Islands', '65859'],
 ['Macedonia', '2062294'],
 ['Mali', '13796354'],
 ['Myanmar [Burma]', '53414374'],
 ['Mongolia', '3086918'],
 ['Macao', '449198'],
 ['Northern Mariana Islands', '53883'],
 ['Martinique', '432900'],
 ['Mauritania', '3205060'],
 ['Montserrat', '9341'],
 ['Malta', '403000'],
 ['Mauritius', '1294104'],
 ['Maldives', '395650'],
 ['Malawi', '15447500'],
 ['Mexico', '112468855'],
 ['Malaysia', '28274729'],
 ['Mozambique', '22061451'],
 ['Namibia', '2128471'],
 ['New Caledonia', '216494'],
 ['Niger', '15878271'],
 ['Norfolk Island', '1828'],
 ['Nigeria', '154000000'],
 ['Nicaragua', '5995928'],
 ['Netherlands', '16645000'],
 ['Norway', '5009150'],
 ['Nepal', '28951852'],
 ['Nauru', '10065'],
 ['Niue', '2166'],
 ['New Zealand', '4252277'],
 ['Oman', '2967717'],
 ['Panama', '3410676'],
 ['Peru', '29907003'],
 ['French Polynesia', '270485'],
 ['Papua New Guinea', '6064515'],
 ['Philippines', '99900177'],
 ['Pakistan', '184404791'],
 ['Poland', '38500000'],
 ['Saint Pierre and Miquelon', '7012'],
 ['Pitcairn Islands', '46'],
 ['Puerto Rico', '3916632'],
 ['Palestine', '3800000'],
 ['Portugal', '10676000'],
 ['Palau', '19907'],
 ['Paraguay', '6375830'],
 ['Qatar', '840926'],
 ['RÃ©union', '776948'],
 ['Romania', '21959278'],
 ['Serbia', '7344847'],
 ['Russia', '140702000'],
 ['Rwanda', '11055976'],
 ['Saudi Arabia', '25731776'],
 ['Solomon Islands', '559198'],
 ['Seychelles', '88340'],
 ['Sudan', '35000000'],
 ['Sweden', '9828655'],
 ['Singapore', '4701069'],
 ['Saint Helena', '7460'],
 ['Slovenia', '2007000'],
 ['Svalbard and Jan Mayen', '2550'],
 ['Slovakia', '5455000'],
 ['Sierra Leone', '5245695'],
 ['San Marino', '31477'],
 ['Senegal', '12323252'],
 ['Somalia', '10112453'],
 ['Suriname', '492829'],
 ['South Sudan', '8260490'],
 ['SÃ£o TomÃ© and PrÃ\xadncipe', '175808'],
 ['El Salvador', '6052064'],
 ['Sint Maarten', '37429'],
 ['Syria', '22198110'],
 ['Swaziland', '1354051'],
 ['Turks and Caicos Islands', '20556'],
 ['Chad', '10543464'],
 ['French Southern Territories', '140'],
 ['Togo', '6587239'],
 ['Thailand', '67089500'],
 ['Tajikistan', '7487489'],
 ['Tokelau', '1466'],
 ['East Timor', '1154625'],
 ['Turkmenistan', '4940916'],
 ['Tunisia', '10589025'],
 ['Tonga', '122580'],
 ['Turkey', '77804122'],
 ['Trinidad and Tobago', '1228691'],
 ['Tuvalu', '10472'],
 ['Taiwan', '22894384'],
 ['Tanzania', '41892895'],
 ['Ukraine', '45415596'],
 ['Uganda', '33398682'],
 ['U.S. Minor Outlying Islands', '0'],
 ['United States', '310232863'],
 ['Uruguay', '3477000'],
 ['Uzbekistan', '27865738'],
 ['Vatican City', '921'],
 ['Saint Vincent and the Grenadines', '104217'],
 ['Venezuela', '27223228'],
 ['British Virgin Islands', '21730'],
 ['U.S. Virgin Islands', '108708'],
 ['Vietnam', '89571130'],
 ['Vanuatu', '221552'],
 ['Wallis and Futuna', '16025'],
 ['Samoa', '192001'],
 ['Kosovo', '1800000'],
 ['Yemen', '23495361'],
 ['Mayotte', '159042'],
 ['South Africa', '49000000'],
 ['Zambia', '13460305'],
 ['Zimbabwe', '11651858']]

In [20]:
import pandas as pd

In [32]:
df=pd.DataFrame(all_countries, columns=["Name", "Population"])

In [34]:
df.head()

                   Name Population
0               Andorra      84000
1  United Arab Emirates    4975593
2           Afghanistan   29121286
3   Antigua and Barbuda      86754
4              Anguilla      13254

In [36]:
df.nunique()

Name          250
Population    247
dtype: int64

In [40]:
df.describe()

           Name Population
count       250        250
unique      250        247
top     Andorra          0
freq          1          4

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        250 non-null    object
 1   Population  250 non-null    object
dtypes: object(2)
memory usage: 4.0+ KB

In [44]:
df["Population"] = pd.to_numeric(df["Population"], errors="coerce")

In [46]:
df["Population"].isnull().sum()

np.int64(0)

In [48]:
df[df["Population"] == 0]

                                  Name  Population
8                           Antarctica           0
33                       Bouvet Island           0
95   Heard Island and McDonald Islands           0
231        U.S. Minor Outlying Islands           0

In [52]:
df["Population"] = df["Population"].fillna(df["Population"].median())

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        250 non-null    object
 1   Population  250 non-null    int64
dtypes: int64(1), object(1)
memory usage: 4.0+ KB

In [59]:
df.describe()

         Population
count  2.500000e+02
mean   2.744568e+07
std    1.168626e+08
min    0.000000e+00
25%    1.798562e+05
50%    4.288138e+06
75%    1.542062e+07
max    1.330044e+09

In [61]:
df.nunique()

Name          250
Population    247
dtype: int64

In [63]:
(df["Population"] == 0).sum()

np.int64(4)

In [65]:
df["Population"].isnull().sum()

np.int64(0)

In [69]:
import numpy as np

In [71]:
df["Population"] = df["Population"].replace(0, np.nan)

In [73]:
df["Population"] = df["Population"].fillna(df["Population"].median())

In [75]:
(df["Population"] == 0).sum()

np.int64(0)

In [77]:
df["Population"].isnull().sum()

np.int64(0)

In [81]:
df.to_csv("cleaned_data/data.csv",index=False)