In [3]:
#data analysis and manipulation
import pandas as pd

In [52]:
info ={
    "Name" : ["saket", "bhavya", "rahul"],
    "CGPA" : ["8.1","7,5" ,"8.5"]

}
df = pd.DataFrame(info)
print(df)

print(df.iloc[0])
df.iloc[0,0]
df.describe()

     Name CGPA
0   saket  8.1
1  bhavya  7,5
2   rahul  8.5
Name    saket
CGPA      8.1
Name: 0, dtype: str

         Name CGPA
count       3    3
unique      3    3
top     saket  8.1
freq        1    1

In [23]:
s = pd.Series([1,2,3,4])
print(s)
#index
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
dtype: int64
1
3

In [6]:
#we can assign label values
s = pd.Series([23,24,25,26], index=["Adam", "Eve", "Bob", "charlie"])
print(s)
print(s.index)

Adam       23
Eve        24
Bob        25
charlie    26
dtype: int64
Index(['Adam', 'Eve', 'Bob', 'charlie'], dtype='str')

In [7]:
#vectorization
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1+s2)
s1[0] =100
print(s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [47]:
#dataframe
info ={
    "Name" :["Adam", "Eve", "Bob"],
    "Age" : [23,24,25],
    "GPA" : [9.5, 8.6 , 7.2]
}
df= pd.DataFrame(info)
print(df,type(df))

print(df.index)
print(df.columns)

   Name  Age  GPA
0  Adam   23  9.5
1   Eve   24  8.6
2   Bob   25  7.2 <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='str')

In [9]:
df

   Name  Age  GPA
0  Adam   23  9.5
1   Eve   24  8.6
2   Bob   25  7.2

In [10]:
#create dataframe using NUMPY array
import numpy as np
np_arr = np.array([[1,2,3], [4,5,6]])

df = pd.DataFrame(np_arr, columns=["A", "B", "c"])

In [11]:
df

   A  B  c
0  1  2  3
1  4  5  6